const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const cp = require('node:child_process');
const html = fs.readFileSync('public/index.html', 'utf8');
const app = fs.readFileSync('public/app.js', 'utf8');
const report = fs.readFileSync('public/report.js', 'utf8');
const indigo = fs.readFileSync('public/midnight-indigo.css', 'utf8');
for (const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) new vm.Script(match[1]);
new vm.Script(app);
new vm.Script(report);
assert(html.includes('value="midnight-indigo"'), 'Tema 3 must be selectable');
assert(app.includes("saved==='monochrome'||saved==='midnight-indigo'"), 'Tema 3 must persist');
assert(indigo.includes('html[data-skin="midnight-indigo"][data-theme="dark"]'), 'Tema 3 must support dark mode');
const template = text => text.match(/var TEMPLATE=String.raw`([\s\S]*?)`;/)[1];
assert.equal(template(report), template(cp.execFileSync('git', ['show', 'HEAD:public/report.js'], {encoding:'utf8'})));
const context = {Date, calendarDay:new Date().toDateString(), reportDateSession:new Date(2020,0,9), render(){}, loadRemote(){}, reportDateInput:{}};
vm.createContext(context);
vm.runInContext(report.match(/  function checkCalendarDay\(\).*\n/)[0], context);
context.checkCalendarDay();
assert.equal(context.reportDateSession.getFullYear(), 2020, 'Selection must survive the same-day timer');
context.calendarDay='old day';context.checkCalendarDay();
assert.equal(context.reportDateSession.toDateString(), new Date().toDateString());
assert(!report.includes('yearAgo'), 'No automatic last-year data');
const memory = new Map();
const sync = {localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)}, navigator:{onLine:true}, apiHeaders:()=>({Authorization:'Bearer test'}), apiFetch:async()=>({ok:true}), connectionError:()=>'',viewYear:2026,viewMonth:8,monthKey:()=> '2026-09',markSaved(){},updateTableInfo(){},lastSavedAt:'12.00',elements:{saveState:{classList:{remove(){}}}}};
vm.createContext(sync);
sync.API_BASE='https://example.test';
vm.runInContext(app.slice(app.indexOf('    var PENDING_KEY='),app.indexOf('    function scheduleRemoteSync()')),sync);
const data={targetSpd:1,targetAkm:2,salesNet:[10],totalStruk:[1]};
const put=id=>memory.set(sync.PENDING_KEY,JSON.stringify({'2026-09':{id,data}}));
(async()=>{
  put('first');sync.apiFetch=async()=>({ok:false,status:500});await sync.syncRemoteMonth();assert(sync.pendingMonths()['2026-09']);
  sync.apiFetch=async()=>{put('new-edit');return{ok:true}};await sync.syncRemoteMonth();assert.equal(sync.pendingMonths()['2026-09'].id,'new-edit');
  sync.apiFetch=async()=>({ok:true});await sync.syncRemoteMonth();assert.deepEqual(Object.keys(sync.pendingMonths()),[]);
  console.log('PASS: syntax, exact template, date rollover, offline queue, edits during save.');
})().catch(error=>{console.error(error);process.exitCode=1});
